
clean:
	@echo "rm .terraform"
	@rm -f .terraform.lock.hcl
	@rm -rf .terraform

init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply -auto-approve

destroy:
	terraform destroy -auto-approve

