---
# Source: vault-instance/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file
spec:
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
