---
# Source: jx-git-operator/templates/job-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    git-operator.jenkins.io/kind: git-operator
  name: jx-boot-job-env-vars
type: Opaque
data: {}
