---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: https://www.nuts.frank5.link
spec:
  source:
    path: k8s_base/special/aws/website
