- name: "自动化配置"
  hosts: all
  remote_user: root
  vars:
    sshdconfig: /etc/ssh/sshd_config
    v2ray_address: 0.0.0.0
    v2ray_port: 19327
    v2ray_userid: 02072033-6842-4105-84ea-40f19b93de4f
  tasks:
  - name: "保持远程连接不断开"
    lineinfile: dest='{{ sshdconfig }}' regexp='^#?ClientAliveInterval' line='ClientAliveInterval 60'
  - lineinfile: dest='{{ sshdconfig }}' regexp='^#?ClientAliveCountMax' line='ClientAliveCountMax 30'

  - name: "reload sshd service"
    service: name=sshd state=reloaded

  - name: 下载安装脚本
    get_url:
      url: https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
      dest: /tmp/install-release.sh
      mode: '0755'

  - name: "安装服务器v2ray"
    shell: /tmp/install-release.sh

  - name: "用/usr/local/etc/v2ray/config.json配置v2ray"
    template:
      src: config.json.tmpl
      dest: /usr/local/etc/v2ray/config.json
      mode: 0644

  - name: "start v2ray service"
    service: 
      name: v2ray
      enabled: yes
      state: started