---
# Source: gitea/charts/memcached/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-memcached
  labels:
    app.kubernetes.io/name: memcached
    helm.sh/chart: memcached-4.2.20
    app.kubernetes.io/instance: git
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: memcached
      app.kubernetes.io/instance: git
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memcached
        helm.sh/chart: memcached-4.2.20
        app.kubernetes.io/instance: git
        app.kubernetes.io/managed-by: Helm
    spec:      
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: memcached
          image: docker.io/bitnami/memcached:1.6.6-debian-10-r54
          imagePullPolicy: "IfNotPresent"
          args:
            - /run.sh
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MEMCACHED_USERNAME
              value: ""
            - name: MEMCACHED_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-memcached
                  key: memcached-password
          ports:
            - name: memcache
              containerPort: 11211
          livenessProbe:
            tcpSocket:
              port: memcache
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: memcache
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits: {}
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: false
      volumes:
        - name: tmp
          emptyDir: {}
