---
# Source: gitea/charts/memcached/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: git-memcached
  labels:
    app.kubernetes.io/name: memcached
    helm.sh/chart: memcached-4.2.20
    app.kubernetes.io/instance: git
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  memcached-password: ""
