---
# Source: loki/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: loki
  annotations:
    {}
  name: loki
  namespace: jx-observability
