---
# Source: gitea/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: git-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-9.7.2
    app.kubernetes.io/instance: git
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgresql-password: "Z2l0ZWE="
