---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    namespace: git
    server: https://kubernetes.default.svc
  project: nuts
  source:
    path: k8s_base/special/common/gitea
    directory:
      recurse: true
    repoURL: https://github.com/yantao0527/frank-knife.git
