---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
  # annotations:
  #   link.argocd.argoproj.io/external-link: https://www.nuts.yantao0527.me
spec:
  destination:
    namespace: website
    server: https://kubernetes.default.svc
  project: nuts
  source:
    path: k8s_base/special/nuts/website
    repoURL: https://github.com/yantao0527/frank-knife.git
