filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-observability
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
releases:
- chart: jxgh/grafana-dashboard
  version: 0.2.2
  name: grafana-dashboard
  values:
  - grafana_dashboard.yaml.gotmpl
- chart: grafana/loki
  version: 2.5.0
  name: loki
  values:
  - loki.yaml
- chart: grafana/promtail
  version: 3.5.0
  name: promtail
  values:
  - promtail.yaml
- chart: grafana/tempo
  version: 0.6.8
  name: tempo
  values:
  - tempo.yaml
- chart: grafana/grafana
  version: 6.6.3
  name: grafana
  values:
  - grafana.yaml.gotmpl
- chart: prometheus-community/prometheus
  version: 13.6.0
  name: prometheus
  values:
  - prometheus.yaml
