apiVersion: k3d.io/v1alpha2
kind: Simple
name: nuts
kubeAPI:
  # host: "nuts.yantao0527.me"
  # hostIP: "0.0.0.0"
  hostPort: "6443"
ports:
  - port: 80:80             # http2
    nodeFilters:
      - loadbalancer
  - port: 443:443           # https
    nodeFilters:
      - loadbalancer
  - port: 8200:8200         # vault ui
    nodeFilters:
      - loadbalancer
  - port: 32022:32022       # gitea ssh
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraServerArgs:
      - --no-deploy=traefik
      - --tls-san=yantao0527.me