mirrors:
  docker.io:
    endpoint:
      - http://registry.localhost:5000
  "registry.localhost:5000":
    endpoint:
      - http://registry.localhost:5000

configs:
  registry.cn-hangzhou.aliyuncs.com:
    auth:
      username: yantao0527
      password: mcafee123
