service:
  http:
    type: ClusterIP
    port: 3000
    clusterIP: 
  ssh:
    type: ClusterIP
    port: 32022
    clusterIP: 

ingress:
  enabled: false
  hosts:
    - gitea.nuts.yantao0527.me
  tls:
    - hosts:
        - gitea.nuts.yantao0527.me


