namespace: git
repositories:
- name: gitea
  url: https://dl.gitea.io/charts
releases:
- chart: gitea/gitea
  version: 2.2.2
  name: git
  values:
  - service:
      http:
        type: ClusterIP
        port: 3000
        clusterIP: 
      ssh:
        type: ClusterIP
        port: 32022
        clusterIP: 
  - ingress:
      enabled: false
      hosts:
        - gitea.nuts.{{ requiredEnv "KNIFE_DOMAIN" }}
      tls:
        - hosts:
            - gitea.nuts.{{ requiredEnv "KNIFE_DOMAIN" }}
