---
# Source: tempo/templates/configmap-tempo-query.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-query
  namespace: jx-observability
  labels:
    helm.sh/chart: tempo-0.6.8
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
data:
  tempo-query.yaml: |
    backend: tempo:3100
