---
# Source: tempo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  labels:
    helm.sh/chart: tempo-0.6.8
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
