---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: https://vault.nuts.yantao0527.me:8200
spec:
  destination:
    namespace: jx-vault
    server: https://kubernetes.default.svc
  project: nuts
  source:
    path: k8s_base/special/common/vault
    directory:
      recurse: true
    repoURL: https://github.com/yantao0527/frank-knife.git
