namespace: jx-vault
repositories:
- name: banzaicloud
  url: https://kubernetes-charts.banzaicloud.com
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: banzaicloud/vault-operator
  version: 1.13.2
  name: vault-operator
- chart: jxgh/vault-instance
  version: 1.0.20
  name: vault-instance
  values:
  - vault_instance_values.yaml
