bankVaultsImage: ghcr.io/banzaicloud/bank-vaults:latest
image: vault:1.6.2

ingress:
  enabled: false
  annotation: {}
  spec: {}
  # annotations:
  #   kubernetes.io/ingress.class: istio
  # spec:
  #   rules:
  #     - host: vault-jx.nuts.yantao0527.me
  #       http:
  #         paths:
  #           - path: /
  #             backend:
  #               service:
  #                 name: vault
  #                 port:
  #                   number: 8200
