---
apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  labels:
    app.kubernetes.io/name: vault
    example.com/log-format: json
    global_service: "true"
    vault_cr: vault
spec:
  selector:
    app.kubernetes.io/name: vault
    vault_cr: vault
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  type: LoadBalancer
