apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: demo-es
spec:
  backendType: vault
  data:
  - key: secret/data/bucketrepo/config
    name: config.yaml
    property: config.yaml
  vaultMountPoint: kubernetes
  vaultRole: default
