apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: demo-vault-es
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: webapp
  data:
    - name: username
      key: secret/data/webapp/config
      property: username
    - name: password
      key: secret/data/webapp/config
      property: password
