bases:
- ../../../base/website
configMapGenerator:
- name: nginx-html
  files:
  - html/index.html
  - html/jenkinsx.html
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
patchesStrategicMerge:
- k_website.yaml
- k_website_vs.yaml
- k_http_gw.yaml
- k_https_gw.yaml
- k_addons_vs.yaml
- k_argocd_vs.yaml
- k_dashboard_vs.yaml
- k_gitea_vs.yaml