---
# Source: jx-git-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jx-git-operator
  labels:
    chart: "jx-git-operator-0.0.194"
spec:
  selector:
    matchLabels:
      app: jx-git-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: jx-git-operator
    spec:
      containers:
      - name: jx-git-operator
        image: "ghcr.io/jenkins-x/jx-git-operator:0.0.194"
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/sh"
        - "-c"
        args:
        - "echo 'no custom git initialisation scripts'; jx-git-operator"
        env:
        - name: POLL_DURATION
          value: "20s"
        envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
        resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 30
      serviceAccountName: "jx-git-operator"
