---
# Source: jx-git-operator/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    git-operator.jenkins.io/kind: git-operator
  name: jx-boot
type: Opaque
data:
  url: "aHR0cHM6Ly9naXRodWIuY29tL3lhbnRhbzA1MjcvangzLWtpbmQtdmF1bHQwMi5naXQ="
  username: "eWFudGFvMDUyNw=="
  password: "ZGYwNjUwNmNjNThjNDdjOGIwOTk1MzFhODA1ZmFkMTcxODI1YzY3Mg=="
  gitInitCommands: "ZWNobyAnbm8gY3VzdG9tIGdpdCBpbml0aWFsaXNhdGlvbiBzY3JpcHRzJw=="
