name: Mirror to Gitee Repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:yantao0527/frank-knife.git"
          destination-repo: "git@gitee.com:yantao0527/frank-knife.git"
